# Data Cleaning

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("movie_metadata.csv")
data.head(300)

movie_code  duration  facenumber_in_poster      country       budget  \
0             1     178.0                   0.0          USA  237000000.0   
1             2     169.0                   0.0          USA  300000000.0   
2             3     148.0                   1.0           UK  245000000.0   
3             4     164.0                   0.0          USA  250000000.0   
4             5     132.0                   1.0          USA  263700000.0   
5             6     156.0                   0.0          USA  258000000.0   
6             7     100.0                   1.0          USA  260000000.0   
7             8     141.0                   4.0          USA  250000000.0   
8             9     153.0                   3.0           UK  250000000.0   
9            10     183.0                   0.0          USA  250000000.0   
10           11     169.0                   0.0          USA  209000000.0   
11           12     106.0                   1.0           UK  200000000.0   
12           13     151.0                   2.0          USA  225000000.0   
13           14     150.0                   1.0          USA  215000000.0   
14           15     143.0                   0.0          USA  225000000.0   
15           16     150.0                   4.0          USA  225000000.0   
16           17     173.0                   3.0          USA  220000000.0   
17           18     136.0                   4.0          USA  250000000.0   
18           19     106.0                   1.0          USA  225000000.0   
19           20     164.0                   0.0  New Zealand  250000000.0   
20           21     153.0                   0.0          USA  230000000.0   
21           22     156.0                   0.0          USA  200000000.0   
22           23     186.0                   6.0          USA  225000000.0   
23           24     113.0                   2.0          USA  180000000.0   
24           25     201.0                   0.0  New Zealand  207000000.0   
25           26     194.0                   0.0          USA  200000000.0   
26           27     147.0                   0.0          USA  250000000.0   
27           28     131.0                   0.0          USA  209000000.0   
28           29     124.0                   0.0          USA  150000000.0   
29           30     143.0                   0.0           UK  200000000.0   
..          ...       ...                   ...          ...          ...   
270         271     120.0                   0.0          USA  110000000.0   
271         272     165.0                   1.0          USA  107000000.0   
272         273      82.0                   1.0          USA  109000000.0   
273         274     115.0                   1.0          USA  120000000.0   
274         275     194.0                   1.0          USA  130000000.0   
275         276      84.0                   0.0      Germany  133000000.0   
276         277      97.0                   0.0          USA  105000000.0   
277         278     151.0                   1.0          USA  108000000.0   
278         279      22.0                   0.0          NaN          NaN   
279         280     136.0                   1.0          USA  126000000.0   
280         281     104.0                   0.0     New Line   90000000.0   
281         282     127.0                   1.0          USA   90000000.0   
282         283     171.0                   0.0          USA  103000000.0   
283         284     145.0                   0.0          USA  102000000.0   
284         285     174.0                   1.0           UK  100000000.0   
285         286     144.0                   1.0           UK  150000000.0   
286         287     119.0                   0.0          USA  100000000.0   
287         288     153.0                   0.0          USA  102000000.0   
288         289     140.0                   1.0          USA  100000000.0   
289         290     176.0                   0.0          USA  100000000.0   
2

In [3]:
data.describe() #statdes 

movie_code     duration  facenumber_in_poster        budget  \
count  5042.000000  5028.000000           5029.000000  4.551000e+03   
mean   2521.500000   107.201074              1.371446  3.975262e+07   
std    1455.644359    25.197441              2.013683  2.061149e+08   
min       1.000000     7.000000              0.000000  2.180000e+02   
25%    1261.250000    93.000000              0.000000  6.000000e+06   
50%    2521.500000   103.000000              1.000000  2.000000e+07   
75%    3781.750000   118.000000              2.000000  4.500000e+07   
max    5042.000000   511.000000             43.000000  1.221550e+10   

              gross  num_voted_users  num_user_for_reviews  \
count  4.159000e+03     5.042000e+03           5022.000000   
mean   4.846841e+07     8.368475e+04            272.770808   
std    6.845299e+07     1.384940e+05            377.982886   
min    1.620000e+02     5.000000e+00              1.000000   
25%    5.340988e+06     8.599250e+03             65.000000   
50%    2.551750e+07     3.437100e+04            156.000000   
75%    6.230944e+07     9.634700e+04            326.000000   
max    7.605058e+08     1.689764e+06           5060.000000   

       num_critic_for_reviews  movie_facebook_likes  director_facebook_likes  \
count             4993.000000           5042.000000              4938.000000   
mean               140.194272           7527.457160               686.621709   
std                121.601675          19322.070537              2813.602405   
min                  1.000000              0.000000                 0.000000   
25%                 50.000000              0.000000                 7.000000   
50%                110.000000            166.000000                49.000000   
75%                195.000000           3000.000000               194.750000   
max                813.000000         349000.000000             23000.000000   

       actor_1_facebook_likes  actor_2_facebook_likes  actor_3_facebook_likes  \
count             5035.000000             5029.000000             5020.000000   
mean              6561.323932             1652.080533              645.009761   
std              15021.977635             4042.774685             1665.041728   
min                  0.000000                0.000000                0.000000   
25%                614.500000              281.000000              133.000000   
50%                988.000000              595.000000              371.500000   
75%              11000.000000              918.000000              636.000000   
max             640000.000000           137000.000000            23000.000000   

       cast_total_facebook_likes   imdb_score  
count                5042.000000  5042.000000  
mean                 9700.959143     6.442007  
std                 18165.101925     1.125189  
min                     0.000000     1.600000  
25%                  1411.250000     5.800000  
50%                  3091.000000     6.600000  
75%                 13758.750000     7.200000  
max                656730.000000     9.500000

In [4]:
np.sum(data.isnull()) #number of NA in data

movie_code                     0
duration                      14
facenumber_in_poster          13
country                        4
budget                       491
gross                        883
num_voted_users                0
num_user_for_reviews          20
num_critic_for_reviews        49
movie_facebook_likes           0
director_facebook_likes      104
actor_1_facebook_likes         7
actor_2_facebook_likes        13
actor_3_facebook_likes        22
cast_total_facebook_likes      0
imdb_score                     0
imdb_score_class               0
dtype: int64

In [5]:
# jika nilai NA < 10% maka bisa dihapus 

In [6]:
data['budget']=data['budget'].fillna(3.975262e+07)

In [7]:
np.sum(data.isnull())

movie_code                     0
duration                      14
facenumber_in_poster          13
country                        4
budget                         0
gross                        883
num_voted_users                0
num_user_for_reviews          20
num_critic_for_reviews        49
movie_facebook_likes           0
director_facebook_likes      104
actor_1_facebook_likes         7
actor_2_facebook_likes        13
actor_3_facebook_likes        22
cast_total_facebook_likes      0
imdb_score                     0
imdb_score_class               0
dtype: int64

In [8]:
data['gross']=data['gross'].fillna(4.846841e+07)
data['director_facebook_likes']=data['director_facebook_likes'].fillna(686.621709)
data['duration'] = data['duration'].fillna(107.201074)
data['facenumber_in_poster'] = data['facenumber_in_poster'].fillna(1.371446)
data['num_user_for_reviews'] = data['num_user_for_reviews'].fillna(272.770808)
data['num_critic_for_reviews'] = data['num_critic_for_reviews'].fillna(272.770808)
data['actor_1_facebook_likes'] = data['actor_1_facebook_likes'].fillna(6561.323932)
data['actor_2_facebook_likes'] = data['actor_2_facebook_likes'].fillna(1652.080533)
data['actor_3_facebook_likes'] = data['actor_3_facebook_likes'].fillna(645.009761)
np.sum(data.isnull())

movie_code                   0
duration                     0
facenumber_in_poster         0
country                      4
budget                       0
gross                        0
num_voted_users              0
num_user_for_reviews         0
num_critic_for_reviews       0
movie_facebook_likes         0
director_facebook_likes      0
actor_1_facebook_likes       0
actor_2_facebook_likes       0
actor_3_facebook_likes       0
cast_total_facebook_likes    0
imdb_score                   0
imdb_score_class             0
dtype: int64

In [9]:
# jika NA <10% bisa diabaikan atau imputasi
#jika NA > 15% bisa jadi kandidat yang dihapus, tapi jika korelasi yang kuat dengan variabel lain, jangan dihapus tapi di imputasi
# jika NA > 50% maka variabel dapat dihapus

In [10]:
data['gross']=data['gross'].fillna(data['budget'].mean())
data['director_facebook_likes']=data['director_facebook_likes'].fillna(data['director_facebook_likes'].mean())
data['duration'] = data['duration'].fillna(data['duration'].mean())
data['facenumber_in_poster'] = data['facenumber_in_poster'].fillna(data['facenumber_in_poster'].mean())
data['num_user_for_reviews'] = data['num_user_for_reviews'].fillna(data['num_user_for_reviews'].mean())
data['num_critic_for_reviews'] = data['num_critic_for_reviews'].fillna(data['num_critic_for_reviews'].mean())
data['actor_1_facebook_likes'] = data['actor_1_facebook_likes'].fillna(data['actor_1_facebook_likes'].mean())
data['actor_2_facebook_likes'] = data['actor_2_facebook_likes'].fillna(data['actor_2_facebook_likes'].mean())
data['actor_3_facebook_likes'] = data['actor_3_facebook_likes'].fillna(data['actor_3_facebook_likes'].mean())
np.sum(data.isnull())

movie_code                   0
duration                     0
facenumber_in_poster         0
country                      4
budget                       0
gross                        0
num_voted_users              0
num_user_for_reviews         0
num_critic_for_reviews       0
movie_facebook_likes         0
director_facebook_likes      0
actor_1_facebook_likes       0
actor_2_facebook_likes       0
actor_3_facebook_likes       0
cast_total_facebook_likes    0
imdb_score                   0
imdb_score_class             0
dtype: int64

In [11]:
# untuk imputasi dengan median maka harus di cek dulu distribusinya apakah normal atau tidak. kalau distribusi tidak normal maka tidak dapat digunakan median.

In [12]:
((data['country'].mode()))

0    USA
dtype: object

In [13]:
from scipy.stats import mode

# mengisi missing value dengan modus untuk qualitative /categorical data 

data['country']=data['country'].fillna(data['country']).dropna().mode()[0]
np.sum(data.isnull())

movie_code                   0
duration                     0
facenumber_in_poster         0
country                      0
budget                       0
gross                        0
num_voted_users              0
num_user_for_reviews         0
num_critic_for_reviews       0
movie_facebook_likes         0
director_facebook_likes      0
actor_1_facebook_likes       0
actor_2_facebook_likes       0
actor_3_facebook_likes       0
cast_total_facebook_likes    0
imdb_score                   0
imdb_score_class             0
dtype: int64

In [14]:
# mengatasi outlier
# univariat itu kalau ada outlier di lihat per variabel 
# di multivariat dideteksi outlier secara simultan jadinya kalau outlier satu pengamatan dihapus


In [15]:
from scipy.stats import stats
z= np.abs(stats.zscore(data._get_numeric_data()))
print(z)
data=data[(z<3).all(axis=1)]
print(data.shape)

[[1.73170732 2.81395543 0.68201074 ... 0.12640574 0.26795566 1.29590414]
 [1.73102027 2.4562438  0.68201074 ... 0.21368996 2.12786442 0.58484214]
 [1.73033322 1.62158335 0.18471742 ... 0.29135456 0.11005934 0.3181939 ]
 ...
 [1.73033322 1.24010965 0.68201074 ... 0.38827014 0.53409672 0.12621985]
 [1.73102027 0.28621199 1.80445584 ... 0.09391165 0.40273293 0.12621985]
 [1.73170732 0.68366935 0.68201074 ... 0.37863877 0.52512258 0.1404284 ]]
(4258, 17)


In [16]:
data

movie_code  duration  facenumber_in_poster country       budget  \
4              5     132.0              1.000000     USA  263700000.0   
6              7     100.0              1.000000     USA  260000000.0   
11            12     106.0              1.000000     USA  200000000.0   
13            14     150.0              1.000000     USA  215000000.0   
15            16     150.0              4.000000     USA  225000000.0   
18            19     106.0              1.000000     USA  225000000.0   
21            22     156.0              0.000000     USA  200000000.0   
23            24     113.0              2.000000     USA  180000000.0   
27            28     131.0              0.000000     USA  209000000.0   
38            39     142.0              0.000000     USA  200000000.0   
39            40     125.0              0.000000     USA  170000000.0   
40            41     106.0              0.000000     USA  200000000.0   
41            42     123.0              2.000000     USA  200000000.0   
43            44     118.0              0.000000     USA  200000000.0   
48            49     114.0              1.000000     USA  195000000.0   
50            51     116.0              2.000000     USA  200000000.0   
54            55      93.0              0.000000     USA   39752620.0   
56            57     122.0              4.000000     USA  185000000.0   
58            59      91.0              2.000000     USA  140000000.0   
59            60     158.0              0.000000     USA  200000000.0   
62            63     110.0              2.000000     USA  180000000.0   
64            65     144.0              6.000000     USA  178000000.0   
67            68      94.0              2.000000     USA  175000000.0   
70            71     106.0              2.000000     USA  170000000.0   
71            72     112.0              2.000000     USA  145000000.0   
75            76     176.0              0.000000     USA  175000000.0   
76            77     118.0              4.000000     USA  175000000.0   
83            84     109.0              3.000000     USA   39752620.0   
84            85     128.0              2.000000     USA  175000000.0   
87            88     130.0              2.000000     USA  190000000.0   
...          ...       ...                   ...     ...          ...   
5011        5012     109.0              3.000000     USA   35000000.0   
5012        5013      79.0              0.000000     USA      24000.0   
5013        5014      80.0              0.000000     USA   39752620.0   
5014        5015     100.0              0.000000     USA      23000.0   
5015        5016      90.0              2.000000     USA      25000.0   
5016        5017      90.0              1.000000     USA      22000.0   
5017        5018     120.0              1.000000     USA      20000.0   
5018        5019      91.0              0.000000     USA   39752620.0   
5020        5021      85.0              0.000000     USA      15000.0   
5021        5022      60.0              0.000000     USA      15000.0   
5022        5023      88.0              2.000000     USA      15000.0   
5023        5024      78.0              0.000000     USA      20000.0   
5024        5025     108.0              2.000000     USA      10000.0   
5025        5026     110.0              1.000000     USA       4500.0   
5026        5027      90.0              0.000000     USA      10000.0   
5027        5028      83.0              0.000000     USA      10000.0   
5028        5029     111.0              0.000000     USA    1000000.0   
5029        5030      84.0              2.000000     USA   39752620.0   
5030        5031      82.0              1.371446     USA     200000.0   
5031        5032      98.0              1.000000     USA   39752620.0   
5032        5033      77.0              0.000000     USA       7000.0   
5033        5034      80.0              0.000000     USA       7000.0   
5034        5035      81.0              0.000000     USA       7