# Missing Value

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("tugas3.csv")

In [3]:
np.sum(data.isnull())

No          0
year        0
month       0
day         0
hour        0
pm2.5    2067
DEWP        0
TEMP        0
PRES        0
cbwd        0
Iws         0
Is          0
Ir          0
dtype: int64

In [4]:
data.describe()

No          year         month           day          hour  \
count  43824.000000  43824.000000  43824.000000  43824.000000  43824.000000   
mean   21912.500000   2012.000000      6.523549     15.727820     11.500000   
std    12651.043435      1.413842      3.448572      8.799425      6.922266   
min        1.000000   2010.000000      1.000000      1.000000      0.000000   
25%    10956.750000   2011.000000      4.000000      8.000000      5.750000   
50%    21912.500000   2012.000000      7.000000     16.000000     11.500000   
75%    32868.250000   2013.000000     10.000000     23.000000     17.250000   
max    43824.000000   2014.000000     12.000000     31.000000     23.000000   

              pm2.5          DEWP          TEMP          PRES           Iws  \
count  41757.000000  43824.000000  43824.000000  43824.000000  43824.000000   
mean      98.613215      1.817246     12.448521   1016.447654     23.889140   
std       92.050387     14.433440     12.198613     10.268698     50.010635   
min        0.000000    -40.000000    -19.000000    991.000000      0.450000   
25%       29.000000    -10.000000      2.000000   1008.000000      1.790000   
50%       72.000000      2.000000     14.000000   1016.000000      5.370000   
75%      137.000000     15.000000     23.000000   1025.000000     21.910000   
max      994.000000     28.000000     42.000000   1046.000000    585.600000   

                 Is            Ir  
count  43824.000000  43824.000000  
mean       0.052734      0.194916  
std        0.760375      1.415867  
min        0.000000      0.000000  
25%        0.000000      0.000000  
50%        0.000000      0.000000  
75%        0.000000      0.000000  
max       27.000000     36.000000

In [5]:
data['pm2.5']=data['pm2.5'].fillna(data['pm2.5'].mean())

In [6]:
np.sum(data.isnull())

No       0
year     0
month    0
day      0
hour     0
pm2.5    0
DEWP     0
TEMP     0
PRES     0
cbwd     0
Iws      0
Is       0
Ir       0
dtype: int64

In [7]:
from sklearn.feature_selection import f_regression
x=data.iloc[:,6:9]
y = data.iloc[:,5]
import statsmodels.formula.api as stat

In [8]:
model1 = stat.ols("y ~ x" , data=data).fit()
print(model1.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.195
Model:                            OLS   Adj. R-squared:                  0.195
Method:                 Least Squares   F-statistic:                     3549.
Date:                Sat, 09 Mar 2019   Prob (F-statistic):               0.00
Time:                        15:58:35   Log-Likelihood:            -2.5454e+05
No. Observations:               43824   AIC:                         5.091e+05
Df Residuals:                   43820   BIC:                         5.091e+05
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1609.8395     71.541     22.502      0.0

# Missing Value dan Outlier

In [9]:
from scipy.stats import stats
z= np.abs(stats.zscore(data._get_numeric_data()))
print(z)
data2=data[(z<3).all(axis=1)]
print(data2.shape)

[[1.73201129 1.41460097 1.60170963 ... 0.44189385 0.06935299 0.13766709]
 [1.73193224 1.41460097 1.60170963 ... 0.37930644 0.06935299 0.13766709]
 [1.73185319 1.41460097 1.60170963 ... 0.34351365 0.06935299 0.13766709]
 ...
 [1.73185319 1.41460097 1.58805238 ... 4.37533654 0.06935299 0.13766709]
 [1.73193224 1.41460097 1.58805238 ... 4.45572036 0.06935299 0.13766709]
 [1.73201129 1.41460097 1.58805238 ... 4.51830776 0.06935299 0.13766709]]
(40995, 13)


In [12]:
x2=data2.iloc[:,6:9]
y2 = data2.iloc[:,5]
model2 = stat.ols("y2 ~ x2" , data=data2).fit()
print(model2.summary())

                            OLS Regression Results                            
Dep. Variable:                     y2   R-squared:                       0.206
Model:                            OLS   Adj. R-squared:                  0.206
Method:                 Least Squares   F-statistic:                     3544.
Date:                Sat, 09 Mar 2019   Prob (F-statistic):               0.00
Time:                        15:59:39   Log-Likelihood:            -2.3118e+05
No. Observations:               40995   AIC:                         4.624e+05
Df Residuals:                   40991   BIC:                         4.624e+05
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1274.1673     62.317     20.446      0.0

# Missing Value dan Transformasi

In [13]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(-20,20))
data_potong = data.iloc[:,5:9]
scaler.fit(data_potong)
x_scaled = scaler.transform(data_potong)
x_scaled= pd.DataFrame(x_scaled)
x_scaled.tail()

C:\Users\ika\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


0          1          2          3
43819 -19.678068 -10.000000  -8.852459  11.272727
43820 -19.597586  -9.411765  -9.508197  11.272727
43821 -19.597586  -9.411765  -9.508197  11.272727
43822 -19.678068  -9.411765 -10.163934  11.272727
43823 -19.517103  -8.823529  -9.508197  11.272727

In [15]:
x3=data_potong.iloc[:,1:4]
y3 = data_potong.iloc[:,0]
model3 = stat.ols("y3 ~ x3" , data=data_potong).fit()
print(model3.summary())

                            OLS Regression Results                            
Dep. Variable:                     y3   R-squared:                       0.195
Model:                            OLS   Adj. R-squared:                  0.195
Method:                 Least Squares   F-statistic:                     3549.
Date:                Sat, 09 Mar 2019   Prob (F-statistic):               0.00
Time:                        16:06:46   Log-Likelihood:            -2.5454e+05
No. Observations:               43824   AIC:                         5.091e+05
Df Residuals:                   43820   BIC:                         5.091e+05
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1609.8395     71.541     22.502      0.0

# missing Value, Outlier, dan Transformasi

In [18]:
# data2 merupakan data yang sudah dibuang outliernya, dilakukan normalisasi
from sklearn.preprocessing import normalize
xx = data2.iloc[:,5:9]
xnorm = normalize(xx,norm='l2')
xnorm = pd.DataFrame(xnorm)
xnorm.tail()

0         1         2         3
40990  0.007735 -0.021271 -0.004834  0.999732
40991  0.007735 -0.021271 -0.004834  0.999732
40992  0.007735 -0.021271 -0.002901  0.999740
40993  0.006768 -0.021271 -0.001934  0.999749
40994  0.011602 -0.021270 -0.001934  0.999705

In [19]:
x4=xnorm.iloc[:,1:4]
y4 = xnorm.iloc[:,0]
model4 = stat.ols("y4 ~ x4" , data=xnorm).fit()
print(model4.summary())

                            OLS Regression Results                            
Dep. Variable:                     y4   R-squared:                       0.907
Model:                            OLS   Adj. R-squared:                  0.907
Method:                 Least Squares   F-statistic:                 1.338e+05
Date:                Sat, 09 Mar 2019   Prob (F-statistic):               0.00
Time:                        16:14:00   Log-Likelihood:                 98145.
No. Observations:               40995   AIC:                        -1.963e+05
Df Residuals:                   40991   BIC:                        -1.962e+05
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      6.4297      0.011    568.345      0.0